# Generated by Django 5.1.5 on 2025-02-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="user",
        ),
        migrations.AddField(
            model_name="transaction",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
